@startuml
autonumber
title "Client Credentials Flow"


participant "Client App" as Client
participant "Authorization Server" as AuthServer

Client -> AuthServer : Client Authentication
AuthServer -> Client : Access Token
@enduml