@startuml
autonumber
title "resource owner password credentials Flow"


participant "Client App" as Client
participant "Authorization Server" as AuthServer

Client -> AuthServer : Resource Owner Password Credentials
AuthServer -> Client : Access Token(w/ optional Refresh Token)
@enduml